# Generated by Django 5.2.4 on 2025-07-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='like',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='category',
            field=models.CharField(choices=[('1', 'Цветы'), ('2', 'Семена'), ('3', 'Игрушки'), ('4', 'Разное')], max_length=1, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
