# Generated by Django 5.2.4 on 2025-07-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': 'Зарегистрированные пользователи'},
        ),
    ]
