# Generated by Django 5.2.4 on 2025-07-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_userinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
