# Generated by Django 5.2.4 on 2025-07-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_catalog_like_alter_catalog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='category',
            field=models.CharField(choices=[('Цветы', 'Цветы'), ('Семена', 'Семена'), ('Игрушки', 'Игрушки'), ('Разное', 'Разное')], max_length=50, verbose_name='Категория'),
        ),
    ]
