# Generated by Django 5.2.4 on 2025-07-25 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_userproduct_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.stocks', verbose_name='Акция'),
        ),
    ]
