# Generated by Django 5.2.4 on 2025-07-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='discount',
            field=models.CharField(choices=[('3', '3%'), ('5', '5%'), ('10', '10%'), ('15', '15%'), ('20', '20%'), ('30', '30%'), ('50', '50%')], max_length=50, verbose_name='Процент скидки'),
        ),
    ]
