# Generated by Django 5.2.4 on 2025-07-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_stocks_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default=None, max_length=100, verbose_name='Краткое описание'),
        ),
    ]
