# Generated by Django 5.2.4 on 2025-08-09 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_short_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('name_product', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('category_product', models.CharField(max_length=100, verbose_name='Категория продукта')),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продукта')),
                ('count_product', models.IntegerField(verbose_name='Количество')),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('date_status', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Обработка'), ('assembly', 'Сборка'), ('assembled', 'Собран'), ('delivery', 'Доставка'), ('cancelled', 'Отменен'), ('rejection', 'Отказ'), ('completed', 'Завершен')], max_length=50, verbose_name='Статус заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
