# Generated by Django 5.2.4 on 2025-08-09 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_orderhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='category_product',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='count_product',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='name_product',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='price_product',
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date_status',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('category_product', models.CharField(max_length=100, verbose_name='Категория продукта')),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продукта')),
                ('count_product', models.IntegerField(verbose_name='Количество')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.orderhistory')),
            ],
        ),
    ]
