# Generated by Django 5.2.4 on 2025-08-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_orderhistory_category_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='order_number',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
