# Generated by Django 5.2.4 on 2025-08-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_orderhistory_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='order_number',
            field=models.CharField(max_length=20, verbose_name='Номер заказа'),
        ),
    ]
